import { app, ipcMain, Menu, shell, type IpcMainInvokeEvent } from 'electron'
import { existsSync } from 'fs'
import { dirname } from 'path'
import { IPC, type AppState, type Settings, type UpdateSettingsResult } from '@shared/types'
import { isValidAccelerator } from '@shared/accelerator'
import {
  beginDrag,
  endDrag,
  getAppearance,
  getPopupWindow,
  hidePopup,
  setKeyboardCapture
} from './window'
import { isValidMaxHistory, type Store } from './store'
import type { ClipboardWatcher } from './clipboardWatcher'
import type { SettingsController } from './settings'

export interface IpcDeps {
  store: Store
  watcher: ClipboardWatcher
  /** Applies validated settings patches, including OS side effects. */
  settings: SettingsController
  quit(): void
}

class ValidationError extends Error {}

/** Only accept IPC from our own popup window. */
function assertTrustedSender(e: IpcMainInvokeEvent): void {
  const win = getPopupWindow()
  if (!win || e.sender !== win.webContents) {
    throw new Error('IPC from untrusted sender')
  }
}

function handle<A extends unknown[], R>(channel: string, fn: (...args: A) => R | Promise<R>): void {
  ipcMain.handle(channel, (e, ...args) => {
    assertTrustedSender(e)
    return fn(...(args as A))
  })
}

// ---------- payload validation ----------

function validateId(v: unknown): string {
  // Item ids are UUIDs generated by the store.
  if (typeof v !== 'string' || !/^[0-9a-f-]{1,64}$/i.test(v)) {
    throw new ValidationError('invalid item id')
  }
  return v
}

const SETTINGS_VALIDATORS: { [K in keyof Settings]: (v: unknown) => boolean } = {
  maxHistory: isValidMaxHistory,
  shortcut: (v) => typeof v === 'string' && isValidAccelerator(v),
  launchAtLogin: (v) => typeof v === 'boolean',
  paused: (v) => typeof v === 'boolean',
  clearOnQuit: (v) => typeof v === 'boolean'
}

function validateSettingsPatch(v: unknown): Partial<Settings> {
  if (!v || typeof v !== 'object' || Array.isArray(v)) {
    throw new ValidationError('settings patch must be an object')
  }
  const patch: Record<string, unknown> = {}
  for (const [key, value] of Object.entries(v)) {
    const validate = SETTINGS_VALIDATORS[key as keyof Settings]
    if (!validate) throw new ValidationError(`unknown setting: ${key}`)
    if (!validate(value)) throw new ValidationError(`invalid value for ${key}`)
    patch[key] = value
  }
  return patch as Partial<Settings>
}

// ---------- handlers ----------

export function registerIpc(deps: IpcDeps): void {
  const { store, watcher, settings } = deps

  handle(IPC.getState, (): AppState => ({
    history: store.getHistory(),
    settings: store.getSettings(),
    platform: process.platform,
    version: app.getVersion(),
    appearance: getAppearance(),
    runtime: settings.runtime()
  }))

  const paste = (id: string): void => {
    const item = store.findById(id)
    if (!item) return
    watcher.writeText(item.text)
    hidePopup()
  }

  handle(IPC.pasteItem, (id: unknown) => paste(validateId(id)))

  handle(IPC.showItemMenu, (id: unknown) => {
    const itemId = validateId(id)
    const win = getPopupWindow()
    const item = store.findById(itemId)
    if (!win || !item) return
    Menu.buildFromTemplate([
      { label: 'Copy', click: () => paste(itemId) },
      { label: item.pinned ? 'Unpin' : 'Pin', click: () => store.togglePin(itemId) },
      { type: 'separator' },
      { label: 'Delete', click: () => store.remove(itemId) }
    ]).popup({ window: win })
  })

  handle(IPC.deleteItem, (id: unknown) => store.remove(validateId(id)))
  handle(IPC.togglePin, (id: unknown) => store.togglePin(validateId(id)))
  handle(IPC.clearAll, () => store.clearUnpinned())

  handle(IPC.updateSettings, (patch: unknown): UpdateSettingsResult => {
    try {
      return settings.update(validateSettingsPatch(patch))
    } catch (err) {
      if (err instanceof ValidationError) {
        return {
          ok: false,
          settings: store.getSettings(),
          runtime: settings.runtime(),
          error: err.message
        }
      }
      throw err
    }
  })

  handle(IPC.setShortcutRecording, (active: unknown) => {
    if (typeof active !== 'boolean') throw new ValidationError('active must be a boolean')
    settings.setRecording(active)
    setKeyboardCapture(active)
  })

  handle(IPC.hidePopup, () => hidePopup())
  handle(IPC.beginDrag, () => beginDrag())
  handle(IPC.endDrag, () => endDrag())
  handle(IPC.showDataFile, () => {
    // Before the first save there is no file yet; show the folder instead.
    const file = store.getFilePath()
    if (existsSync(file)) shell.showItemInFolder(file)
    else void shell.openPath(dirname(file))
  })

  handle(IPC.quit, () => deps.quit())
}
