import { ipcMain, type IpcMainInvokeEvent } from 'electron'
import { IPC, type AppState, type Settings, type UpdateSettingsResult } from '@shared/types'
import { getPopupWindow, hidePopup } from './window'
import { isValidMaxHistory, type Store } from './store'
import type { ClipboardWatcher } from './clipboardWatcher'

export interface IpcDeps {
  store: Store
  watcher: ClipboardWatcher
  /** Apply a validated settings patch (including side effects); may reject parts of it. */
  updateSettings(patch: Partial<Settings>): UpdateSettingsResult
  quit(): void
}

class ValidationError extends Error {}

/** Only accept IPC from our own popup window. */
function assertTrustedSender(e: IpcMainInvokeEvent): void {
  const win = getPopupWindow()
  if (!win || e.sender !== win.webContents) {
    throw new Error('IPC from untrusted sender')
  }
}

function handle<A extends unknown[], R>(channel: string, fn: (...args: A) => R | Promise<R>): void {
  ipcMain.handle(channel, (e, ...args) => {
    assertTrustedSender(e)
    return fn(...(args as A))
  })
}

// ---------- payload validation ----------

function validateId(v: unknown): string {
  // Item ids are UUIDs generated by the store.
  if (typeof v !== 'string' || !/^[0-9a-f-]{1,64}$/i.test(v)) {
    throw new ValidationError('invalid item id')
  }
  return v
}

const SETTINGS_VALIDATORS: { [K in keyof Settings]: (v: unknown) => boolean } = {
  maxHistory: isValidMaxHistory,
  shortcut: (v) => typeof v === 'string' && v.length <= 100,
  launchAtLogin: (v) => typeof v === 'boolean',
  paused: (v) => typeof v === 'boolean',
  clearOnQuit: (v) => typeof v === 'boolean'
}

function validateSettingsPatch(v: unknown): Partial<Settings> {
  if (!v || typeof v !== 'object' || Array.isArray(v)) {
    throw new ValidationError('settings patch must be an object')
  }
  const patch: Record<string, unknown> = {}
  for (const [key, value] of Object.entries(v)) {
    const validate = SETTINGS_VALIDATORS[key as keyof Settings]
    if (!validate) throw new ValidationError(`unknown setting: ${key}`)
    if (!validate(value)) throw new ValidationError(`invalid value for ${key}`)
    patch[key] = value
  }
  return patch as Partial<Settings>
}

// ---------- handlers ----------

export function registerIpc(deps: IpcDeps): void {
  const { store, watcher } = deps

  handle(IPC.getState, (): AppState => ({
    history: store.getHistory(),
    settings: store.getSettings(),
    platform: process.platform
  }))

  handle(IPC.pasteItem, (id: unknown) => {
    const item = store.findById(validateId(id))
    if (!item) return
    watcher.writeText(item.text)
    hidePopup()
  })

  handle(IPC.deleteItem, (id: unknown) => store.remove(validateId(id)))
  handle(IPC.togglePin, (id: unknown) => store.togglePin(validateId(id)))
  handle(IPC.clearAll, () => store.clearUnpinned())

  handle(IPC.updateSettings, (patch: unknown): UpdateSettingsResult => {
    try {
      return deps.updateSettings(validateSettingsPatch(patch))
    } catch (err) {
      if (err instanceof ValidationError) {
        return { ok: false, settings: store.getSettings(), error: err.message }
      }
      throw err
    }
  })

  handle(IPC.hidePopup, () => hidePopup())
  handle(IPC.quit, () => deps.quit())
}
